name: yolov4-gpu

channels:
- anaconda
- conda-forge
dependencies:
  - python==3.7
  - pip
  - matplotlib
  - cudnn
  - cudatoolkit==10.1.243
  - moviepy
  - pypdf2
  - pip:
    - tensorflow-gpu
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - pytesseract
