name: TestStripDX

channels:
  - anaconda
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pytorch
  - torchvision 
  - pytorch-cuda=11.8 
  - ultralytics
  - matplotlib
  - moviepy
  - pypdf2
  - opencv
  - lxml
  - easydict
  - pillow
