name: TestStripDX

channels:
- anaconda
- conda-forge
dependencies:
  - python==3.7.2
  - pip
  - matplotlib
  - moviepy
  - pypdf2
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - easydict
    - pillow
