name: yolov4-cpu

channels:
- anaconda
- conda-forge
dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - moviepy
  - pypdf2
  - pip:
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - tensorflow
    - absl-py
    - easydict
    - pillow
    - pytesseract
